### PR TITLE
WIP: Autoconfiguration & Routing

### PR DESCRIPTION
**Pull request by s3lph**
This PR merges auto-configuration and routing, as implemented as part of my BSc thesis (the NDN-ACUTE and NDVR protocols).

WIP; TODO:
- [ ] Command line flags for configuration of both features are only partially present
- [ ] Two tests from the "simulation" modules are still failing

### CODE REVIEW

**Comment by blacksheeep** [comment]
For two tests, timeout occur.
Could you check on that?

**Comment by s3lph** [comment]
They reproducibly work fine on my machine.  
Could this be caused by scheduling/resource issues? In those two tests, I'm starting multiple PiCN stacks and have them communicate with each other. This could be something similar than the issues I had when running the measurements for my evaluation on my private server, where they were getting timeouts most of the time.

**Comment by blacksheeep** [comment]
Could increasing the timeout on the requestor's side be a solution?

**Comment by blacksheeep** [comment]
When I run those tests on my machine, I get the same errors. I will merge it an skip the test until we find a solution.

**Pull request merged**
